import { useMemo } from 'react';
import { Platform, StyleSheet } from 'react-native';

import { useKelivoTheme } from '../../ui/theme';

export interface AppPalette {
  bg: string;
  surface: string;
  surfaceAlt: string;
  surfaceSunken: string;
  border: string;
  borderStrong: string;
  accent: string;
  accentPressed: string;
  accentSoft: string;
  accentBorder: string;
  accentText: string;
  text: string;
  textSecondary: string;
  textMuted: string;
  textMutedSolid: string;
  textOnAccent: string;
  textOnDanger: string;
  mediaOverlayText: string;
  danger: string;
  dangerBg: string;
  dangerBorder: string;
  warning: string;
  edit: string;
  success: string;
  placeholder: string;
  scrim: string;
  userBubble: string;
  userBubbleBorder: string;
  userEditBubble: string;
  userEditBorder: string;
  frostedSurface: string;
}

const lightPalette: AppPalette = {
  bg: '#F7F7F7',
  surface: '#FFFFFF',
  surfaceAlt: '#F0F0F0',
  surfaceSunken: '#EFEFEF',
  border: 'rgba(0, 0, 0, 0.10)',
  borderStrong: 'rgba(0, 0, 0, 0.14)',
  accent: '#4D5C92',
  accentPressed: '#3D4B7A',
  accentSoft: '#DCE1FF',
  accentBorder: '#C6D0FF',
  accentText: '#4D5C92',
  text: '#202020',
  textSecondary: '#646464',
  textMuted: '#9A9A9A55',
  textMutedSolid: '#9A9A9A',
  textOnAccent: '#FFFFFF',
  textOnDanger: '#FFFFFF',
  mediaOverlayText: '#FFFFFF',
  danger: '#BB0947',
  dangerBg: '#FDDADE',
  dangerBorder: 'rgba(187, 9, 71, 0.28)',
  warning: '#D97706',
  edit: '#2563EB',
  success: '#16A34A',
  placeholder: '#9CA3AF',
  scrim: 'rgba(0, 0, 0, 0.32)',
  userBubble: '#F3F4F6',
  userBubbleBorder: '#E5E7EB',
  userEditBubble: '#EEF2FF',
  userEditBorder: '#C7D2FE',
  frostedSurface: 'rgba(255, 255, 255, 0.72)',
};

const darkPalette: AppPalette = {
  bg: '#101217',
  surface: '#14161C',
  surfaceAlt: '#1B1D24',
  surfaceSunken: '#0E1015',
  border: 'rgba(255, 255, 255, 0.13)',
  borderStrong: 'rgba(255, 255, 255, 0.20)',
  accent: '#B8C4FF',
  accentPressed: '#CAD2FF',
  accentSoft: '#2D375D',
  accentBorder: '#53618D',
  accentText: '#B8C4FF',
  text: '#E5E7EF',
  textSecondary: '#B8BBC6',
  textMuted: '#878A9566',
  textMutedSolid: '#878A95',
  textOnAccent: '#1E2A5A',
  textOnDanger: '#65002B',
  mediaOverlayText: '#FFFFFF',
  danger: '#FFB1C2',
  dangerBg: '#5B1130',
  dangerBorder: 'rgba(255, 177, 194, 0.35)',
  warning: '#FFB95F',
  edit: '#93C5FD',
  success: '#6DD58C',
  placeholder: '#878A95',
  scrim: 'rgba(0, 0, 0, 0.62)',
  userBubble: '#242731',
  userBubbleBorder: '#343844',
  userEditBubble: '#222942',
  userEditBorder: '#394469',
  frostedSurface: 'rgba(17, 18, 20, 0.74)',
};

type AppStyles = ReturnType<typeof createChatPaneStyles>;

interface ChatPaneThemeValue {
  palette: AppPalette;
  styles: AppStyles;
  isDark: boolean;
}

export function useChatPaneTheme(): ChatPaneThemeValue {
  const theme = useKelivoTheme();
  return useMemo(
    () => ({
      palette: theme.dark ? darkPalette : lightPalette,
      styles: appStylesByMode[theme.dark ? 'dark' : 'light'],
      isDark: theme.dark,
    }),
    [theme.dark]
  );
}

export const radii = {
  sm: 10,
  md: 14,
  lg: 18,
  xl: 24,
  pill: 999,
} as const;

// 用衬线体呈现品牌标题，呼应 Anthropic 的展示字体气质
export const serifFont = Platform.select({
  ios: 'Georgia',
  android: 'serif',
  default: 'Georgia, "Times New Roman", serif',
});

function createChatPaneStyles(palette: AppPalette) {
  return StyleSheet.create({
  root: {
    flex: 1,
  },
  shell: {
    flex: 1,
    backgroundColor: palette.bg,
  },
  keyboard: {
    flex: 1,
  },
  screenPane: {
    flex: 1,
  },
  screenPaneHidden: {
    display: 'none',
  },
  loadingShell: {
    flex: 1,
    backgroundColor: palette.bg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    marginTop: 12,
    color: palette.textSecondary,
    fontSize: 14,
  },
  topBar: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 12,
    backgroundColor: palette.bg,
  },
  persistenceErrorBanner: {
    marginHorizontal: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: palette.dangerBorder,
    borderRadius: radii.md,
    backgroundColor: palette.dangerBg,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 4,
  },
  persistenceErrorTitle: {
    color: palette.danger,
    fontSize: 14,
    fontWeight: '700',
  },
  persistenceErrorText: {
    color: palette.text,
    fontSize: 12,
    lineHeight: 18,
  },
  persistenceErrorHint: {
    color: palette.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  topHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  topHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  topLeft: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  modelPickerPill: {
    minHeight: 44,
    borderRadius: radii.pill,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 1,
    maxWidth: 252,
    minWidth: 0,
    paddingHorizontal: 14,
    gap: 6,
  },
  modelPickerPillAttention: {
    backgroundColor: palette.accentSoft,
    borderColor: palette.accentBorder,
  },
  modelPickerPillText: {
    flexShrink: 1,
    minWidth: 0,
    color: palette.text,
    fontSize: 15,
    fontWeight: '600',
    maxWidth: 160,
  },
  modelPickerLabelBadge: {
    height: 27,
    borderRadius: radii.sm,
    backgroundColor: palette.accentSoft,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  modelPickerLabelText: {
    color: palette.accentText,
    fontSize: 12,
    fontWeight: '700',
  },
  modelPickerCurrent: {
    flex: 1,
    minWidth: 0,
  },
  modelPickerProviderText: {
    color: palette.textSecondary,
    fontSize: 11,
    fontWeight: '600',
  },
  modelPickerModelText: {
    marginTop: 2,
    color: palette.text,
    fontSize: 15,
    fontWeight: '600',
  },
  modelPickerChevron: {
    color: palette.textSecondary,
    fontSize: 16,
    fontWeight: '700',
  },
  secondaryButton: {
    height: 40,
    minWidth: 60,
    paddingHorizontal: 16,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: palette.borderStrong,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    backgroundColor: palette.surface,
  },
  secondaryButtonText: {
    color: palette.text,
    fontWeight: '600',
    fontSize: 14,
  },
  iconButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    borderWidth: 1,
    borderColor: palette.borderStrong,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surface,
  },
  content: {
    flex: 1,
  },
  settingsContent: {
    padding: 16,
    gap: 16,
  },
  chatContent: {
    padding: 16,
    gap: 18,
  },
  chatHistoryLoadButton: {
    minHeight: 38,
    borderRadius: radii.md,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  chatHistoryLoadText: {
    color: palette.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  sectionTitle: {
    color: palette.text,
    fontSize: 17,
    fontWeight: '600',
    fontFamily: serifFont,
  },
  settingsCard: {
    backgroundColor: palette.surfaceAlt,
    borderRadius: radii.lg,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: palette.border,
    padding: 16,
    gap: 14,
    marginHorizontal: 12,
  },
  settingsCardTitle: {
    color: palette.text,
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 2,
  },
  settingsCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  settingsCardHeaderAction: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  promptTemplateContentInput: {
    minHeight: 112,
    textAlignVertical: 'top',
    paddingTop: 12,
  },
  promptTemplateRow: {
    minHeight: 56,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: radii.md,
    backgroundColor: palette.bg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingLeft: 12,
    paddingRight: 4,
  },
  promptTemplateMain: {
    flex: 1,
    minWidth: 0,
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  promptTemplateTextBlock: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  promptTemplateName: {
    color: palette.text,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  usageSummaryGrid: {
    flexDirection: 'row',
    gap: 8,
  },
  usageSummaryItem: {
    flex: 1,
    minWidth: 0,
    borderRadius: radii.md,
    backgroundColor: palette.bg,
    paddingHorizontal: 10,
    paddingVertical: 12,
    gap: 3,
  },
  usageSummaryValue: {
    color: palette.text,
    fontSize: 18,
    lineHeight: 23,
    fontWeight: '800',
  },
  usageSummaryLabel: {
    color: palette.textSecondary,
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '600',
  },
  usageCostRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 8,
  },
  pricingInputRow: {
    flexDirection: 'row',
    gap: 8,
  },
  pricingInputGroup: {
    flex: 1,
    minWidth: 0,
    gap: 5,
  },
  mediaTaskRow: {
    minHeight: 58,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: radii.md,
    backgroundColor: palette.bg,
    paddingLeft: 12,
    paddingRight: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  mediaTaskInfo: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  mediaTaskState: {
    color: palette.textSecondary,
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '700',
  },
  voiceTargetRow: {
    minHeight: 54,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: radii.md,
    backgroundColor: palette.bg,
    paddingLeft: 12,
    paddingRight: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  providerRow: {
    gap: 10,
    paddingRight: 18,
    paddingVertical: 2,
  },
  projectPresetGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  projectPresetCard: {
    width: '48%',
    minHeight: 92,
    flexGrow: 1,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.bg,
    paddingHorizontal: 12,
    paddingVertical: 11,
    gap: 5,
  },
  projectPresetTitle: {
    color: palette.text,
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '700',
  },
  projectPresetDescription: {
    color: palette.textSecondary,
    fontSize: 12,
    lineHeight: 17,
  },
  providerChip: {
    height: 36,
    paddingHorizontal: 14,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: palette.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.bg,
  },
  providerChipActive: {
    backgroundColor: palette.accent,
    borderColor: palette.accent,
  },
  providerChipText: {
    color: palette.text,
    fontWeight: '500',
    fontSize: 14,
  },
  providerChipTextActive: {
    color: palette.textOnAccent,
  },
  providerDeleteButton: {
    minHeight: 40,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: palette.dangerBorder,
    backgroundColor: palette.dangerBg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingHorizontal: 14,
  },
  providerDeleteButtonText: {
    color: palette.danger,
    fontSize: 13,
    fontWeight: '600',
  },
  fieldGroup: {
    gap: 8,
  },
  settingsEmptyState: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.bg,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  fieldLabel: {
    color: palette.textSecondary,
    fontSize: 13,
    fontWeight: '600',
  },
  input: {
    minHeight: 44,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.bg,
    paddingHorizontal: 14,
    color: palette.text,
    fontSize: 15,
  },
  multilineInput: {
    minHeight: 84,
    paddingTop: 12,
    paddingBottom: 12,
    textAlignVertical: 'top',
  },
  capabilityRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  capabilityChip: {
    borderRadius: radii.pill,
    backgroundColor: palette.surfaceAlt,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  capabilityChipActive: {
    backgroundColor: palette.accent,
    borderColor: palette.accent,
  },
  capabilityText: {
    color: palette.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  capabilityTextActive: {
    color: palette.textOnAccent,
  },
  modelOverridePanel: {
    marginTop: 4,
    borderTopWidth: 1,
    borderTopColor: palette.border,
    paddingTop: 14,
    gap: 10,
  },
  modelOverrideHint: {
    color: palette.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  updateHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  updateTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  updateVersionText: {
    color: palette.textSecondary,
    fontSize: 13,
    lineHeight: 18,
  },
  updateSourceBadge: {
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    color: palette.textSecondary,
    fontSize: 11,
    fontWeight: '700',
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  updateStatusPanel: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.bg,
    padding: 12,
    gap: 5,
  },
  updateStatusTitle: {
    color: palette.text,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
  },
  updateStatusMeta: {
    color: palette.textSecondary,
    fontSize: 12,
    lineHeight: 17,
  },
  updateNotice: {
    color: palette.warning,
    fontSize: 12,
    lineHeight: 17,
  },
  updateActionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  updateActionButton: {
    flex: 1,
    minWidth: 0,
    height: 40,
  },
  actionRow: {
    flexDirection: 'row',
  },
  inlineField: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
  },
  inlineInput: {
    flex: 1,
  },
  primaryButton: {
    height: 48,
    paddingHorizontal: 20,
    borderRadius: radii.pill,
    backgroundColor: palette.accent,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  primaryButtonText: {
    color: palette.textOnAccent,
    fontWeight: '600',
    fontSize: 15,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  modelList: {
    gap: 10,
  },
  candidateModelListFrame: {
    height: 340,
    maxHeight: 340,
    borderRadius: radii.md,
    overflow: 'hidden',
    ...(Platform.OS === 'web' ? { overflowY: 'auto' } as any : {}),
  },
  modelSearchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  modelSearchInput: {
    flex: 1,
  },
  modelFilterTabs: {
    paddingRight: 18,
    gap: 22,
  },
  modelFilterTab: {
    height: 34,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modelFilterTabText: {
    color: palette.textSecondary,
    fontSize: 14,
    fontWeight: '600',
  },
  modelFilterTabTextActive: {
    color: palette.accentText,
    fontWeight: '700',
  },
  modelFilterTabLine: {
    width: '100%',
    height: 2,
    borderRadius: 2,
    backgroundColor: 'transparent',
  },
  modelFilterTabLineActive: {
    backgroundColor: palette.accent,
  },
  modelSearchMeta: {
    marginTop: -8,
    color: palette.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  modelSearchEmpty: {
    minHeight: 70,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modelSearchEmptyText: {
    color: palette.textSecondary,
    fontSize: 13,
    fontWeight: '600',
  },
  loadMoreModelsButton: {
    minHeight: 42,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: palette.borderStrong,
    backgroundColor: palette.bg,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  loadMoreModelsButtonText: {
    color: palette.text,
    fontSize: 13,
    fontWeight: '700',
  },
  modelButton: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  modelButtonActive: {
    borderColor: palette.accentBorder,
    backgroundColor: palette.accentSoft,
  },
  modelSelectArea: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  modelTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  modelName: {
    color: palette.text,
    fontSize: 14,
    fontWeight: '600',
  },
  modelNameActive: {
    color: palette.accentText,
  },
  modelMeta: {
    marginTop: 4,
    color: palette.textSecondary,
    fontSize: 12,
  },
  candidateRow: {
    minHeight: 60,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  addModelButton: {
    minWidth: 48,
    height: 36,
    borderRadius: radii.pill,
    backgroundColor: palette.accent,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  addModelButtonAdded: {
    backgroundColor: palette.surfaceAlt,
    borderWidth: 1,
    borderColor: palette.border,
  },
  addModelButtonText: {
    color: palette.textOnAccent,
    fontSize: 14,
    fontWeight: '700',
  },
  addModelButtonTextAdded: {
    color: palette.textSecondary,
  },
  compactButton: {
    height: 36,
    minWidth: 52,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: palette.borderStrong,
    backgroundColor: palette.surface,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  compactButtonText: {
    color: palette.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  reasoningSliderEndpoints: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  reasoningSliderEndpointText: {
    color: palette.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  reasoningSlider: {
    gap: 6,
  },
  reasoningSliderTrackArea: {
    height: 28,
    justifyContent: 'center',
    position: 'relative',
  },
  reasoningSliderTrack: {
    height: 3,
    borderRadius: 2,
    backgroundColor: palette.borderStrong,
  },
  reasoningSliderThumb: {
    position: 'absolute',
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: palette.accent,
    marginLeft: -9,
    top: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  reasoningSliderLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  reasoningSliderLabel: {
    color: palette.textSecondary,
    fontSize: 12,
    fontWeight: '500',
    paddingHorizontal: 2,
  },
  reasoningSliderLabelActive: {
    color: palette.accent,
    fontWeight: '700',
  },
  messageBubble: {
    maxWidth: '100%',
  },
  searchHighlightedMessage: {
    borderLeftWidth: 3,
    borderLeftColor: palette.warning,
    borderRadius: radii.sm,
    backgroundColor: 'rgba(217, 119, 6, 0.08)',
    paddingLeft: 6,
  },
  userMessageBlock: {
    alignSelf: 'stretch',
    alignItems: 'flex-end',
  },
  userBubble: {
    maxWidth: '86%',
    backgroundColor: palette.userBubble,
    borderWidth: 1,
    borderColor: palette.userBubbleBorder,
    borderRadius: radii.lg,
    borderTopRightRadius: radii.sm,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  assistantBubble: {
    alignSelf: 'stretch',
    paddingHorizontal: 6,
    gap: 12,
  },
  systemMessageBlock: {
    alignSelf: 'stretch',
  },
  systemInstructionCard: {
    borderWidth: 1,
    borderColor: palette.borderStrong,
    borderRadius: radii.lg,
    backgroundColor: palette.surface,
    padding: 12,
    gap: 8,
  },
  systemInstructionHeader: {
    minHeight: 26,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  systemInstructionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  systemInstructionTitle: {
    color: palette.text,
    fontSize: 12,
    fontWeight: '800',
  },
  systemInstructionText: {
    color: palette.textSecondary,
    fontSize: 13,
    lineHeight: 20,
  },
  errorBubble: {
    alignSelf: 'stretch',
    backgroundColor: palette.dangerBg,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: palette.dangerBorder,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  messageRole: {
    marginBottom: 6,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  userRole: {
    color: palette.textSecondary,
  },
  assistantRole: {
    color: palette.accentText,
  },
  modelAvatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: palette.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  messageText: {
    color: palette.text,
    fontSize: 15,
    lineHeight: 24,
  },
  messageStatusText: {
    color: palette.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  messageErrorText: {
    color: palette.danger,
  },
  comparisonContextButton: {
    alignSelf: 'flex-start',
    minHeight: 28,
    paddingHorizontal: 10,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: palette.borderStrong,
    backgroundColor: palette.surface,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  comparisonContextButtonSelected: {
    borderColor: palette.accent,
    backgroundColor: palette.accent,
  },
  comparisonContextButtonText: {
    color: palette.textSecondary,
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '700',
  },
  comparisonContextButtonTextSelected: {
    color: palette.textOnAccent,
  },
  userMessageText: {
    color: palette.text,
    fontSize: 15,
    lineHeight: 24,
  },
  thinkingGlyphRow: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 30,
    height: 30,
  },
  thinkingGlyph: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  thinkingGlyphBand: {
    position: 'absolute',
    width: 22,
    height: 5,
    borderRadius: radii.pill,
    backgroundColor: palette.accent,
  },
  thinkingGlyphCenter: {
    width: 6,
    height: 6,
    borderRadius: radii.pill,
    backgroundColor: palette.surface,
    borderWidth: 1.5,
    borderColor: palette.accent,
  },
  reasoningPanel: {
    borderLeftWidth: 2,
    borderLeftColor: palette.borderStrong,
    paddingLeft: 10,
    paddingVertical: 2,
    gap: 8,
  },
  reasoningPanelHeader: {
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  reasoningPanelTitle: {
    color: palette.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  reasoningPanelAction: {
    color: palette.accentText,
    fontSize: 12,
    fontWeight: '700',
  },
  reasoningPanelText: {
    color: palette.textSecondary,
    fontSize: 13,
    lineHeight: 20,
  },
  tokenUsageText: {
    color: palette.textSecondary,
    fontSize: 11,
    lineHeight: 16,
  },
  assistantFooterRow: {
    minHeight: 26,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  messageActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  messageActionButton: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  attachmentGrid: {
    marginTop: 12,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    alignSelf: 'stretch',
    gap: 8,
  },
  notice: {
    marginHorizontal: 16,
    marginBottom: 8,
    color: palette.warning,
    fontSize: 12,
  },
  settingsNotice: {
    color: palette.warning,
    fontSize: 12,
    lineHeight: 18,
  },
  pendingAttachmentScroller: {
    flexGrow: 0,
    flexShrink: 0,
    maxHeight: 116,
  },
  pendingAttachments: {
    paddingHorizontal: 16,
    paddingBottom: 10,
    alignItems: 'center',
    gap: 8,
  },
  attachButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: palette.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  attachMenuBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 10,
  },
  attachMenu: {
    position: 'absolute',
    bottom: '100%',
    left: 0,
    marginBottom: 8,
    backgroundColor: palette.bg,
    borderRadius: radii.lg,
    paddingVertical: 8,
    paddingHorizontal: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
    minWidth: 180,
  },
  searchMenu: {
    position: 'absolute',
    bottom: '100%',
    left: 0,
    right: 0,
    marginBottom: 8,
    backgroundColor: palette.bg,
    borderRadius: radii.md,
    padding: 12,
    gap: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
    maxHeight: 360,
  },
  searchMenuItem: {
    minHeight: 48,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  searchMenuItemActive: {
    borderColor: palette.accent,
    backgroundColor: palette.accent,
  },
  searchMenuItemTextBlock: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  searchMenuItemTitle: {
    color: palette.text,
    fontSize: 13,
    fontWeight: '700',
  },
  searchMenuItemTitleActive: {
    color: palette.textOnAccent,
  },
  searchMenuItemHint: {
    color: palette.textSecondary,
    fontSize: 11,
    lineHeight: 15,
  },
  searchMenuItemHintActive: {
    color: palette.textOnAccent,
    opacity: 0.88,
  },
  searchMenuEmpty: {
    color: palette.textSecondary,
    fontSize: 12,
    lineHeight: 17,
  },
  searchMenuLink: {
    minHeight: 36,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
  },
  searchMenuLinkText: {
    color: palette.accentText,
    fontSize: 13,
    fontWeight: '700',
  },
  reasoningMenu: {
    position: 'absolute',
    bottom: '100%',
    left: 0,
    right: 0,
    marginBottom: 8,
    backgroundColor: palette.bg,
    borderRadius: radii.md,
    padding: 6,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
  },
  reasoningMenuItem: {
    height: 30,
    minWidth: 48,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingHorizontal: 10,
  },
  reasoningMenuItemActive: {
    borderColor: palette.accent,
    backgroundColor: palette.accent,
  },
  reasoningMenuText: {
    color: palette.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  reasoningMenuTextActive: {
    color: palette.textOnAccent,
    fontWeight: '700',
  },
  parameterMenu: {
    position: 'absolute',
    bottom: '100%',
    left: 0,
    right: 0,
    marginBottom: 8,
    backgroundColor: palette.bg,
    borderRadius: radii.md,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
  },
  parameterMenuScroll: {
    flexGrow: 0,
    flexShrink: 1,
  },
  parameterMenuContent: {
    flexGrow: 0,
    padding: 12,
    gap: 12,
  },
  toolMenuHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  toolMenuTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  toolMenuTitle: {
    color: palette.text,
    fontSize: 16,
    fontWeight: '700',
  },
  toolMenuSubtitle: {
    marginTop: 2,
    color: palette.textSecondary,
    fontSize: 12,
  },
  toolMenuSection: {
    gap: 8,
  },
  toolMenuSectionTitle: {
    color: palette.text,
    fontSize: 14,
    fontWeight: '700',
  },
  toolSegmentRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  toolSegment: {
    minHeight: 30,
    minWidth: 58,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  toolSegmentActive: {
    borderColor: palette.accentBorder,
    backgroundColor: palette.accentSoft,
  },
  toolSegmentText: {
    color: palette.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  toolSegmentTextActive: {
    color: palette.accentText,
    fontWeight: '700',
  },
  toolMenuHint: {
    color: palette.textSecondary,
    fontSize: 12,
    lineHeight: 17,
  },
  parameterResetButton: {
    height: 36,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  parameterResetButtonText: {
    color: palette.text,
    fontSize: 13,
    fontWeight: '700',
  },
  attachMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    height: 44,
    borderRadius: radii.sm,
    paddingHorizontal: 12,
  },
  attachMenuIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: palette.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  attachMenuText: {
    color: palette.text,
    fontWeight: '500',
    fontSize: 15,
  },
  composerWrapper: {
    marginHorizontal: 8,
    marginBottom: 12,
    borderRadius: radii.md,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    overflow: 'visible',
    zIndex: 20,
  },
  composer: {
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 6,
    gap: 4,
  },
  composerInput: {
    alignSelf: 'stretch',
    height: 32,
    maxHeight: 120,
    paddingVertical: 6,
    paddingHorizontal: 2,
    color: palette.text,
    fontSize: 14,
    lineHeight: 20,
    textAlignVertical: 'center',
    ...(Platform.OS === 'web' ? { outlineStyle: 'none' } as any : {}),
  },
  composerFooter: {
    minHeight: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  composerLeftTools: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  composerToolButton: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  composerToolButtonActive: {
    backgroundColor: palette.surfaceAlt,
  },
  sendButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: palette.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendButtonText: {
    color: palette.textOnAccent,
    fontWeight: '700',
    fontSize: 16,
    lineHeight: 18,
  },
  sidebarRoot: {
    flex: 1,
    flexDirection: 'row',
  },
  sidebarScrimBase: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: palette.scrim,
  },
  sidebarPanel: {
    width: '80%',
    maxWidth: 320,
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: palette.bg,
    paddingTop: 20,
    paddingHorizontal: 20,
    paddingBottom: 32,
  },
  sidebarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  sidebarBrand: {
    color: palette.text,
    fontSize: 18,
    fontWeight: '700',
    fontFamily: serifFont,
  },
  sidebarClose: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sidebarNewChat: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    height: 38,
    borderRadius: radii.pill,
    backgroundColor: palette.accent,
    paddingHorizontal: 14,
    alignSelf: 'stretch',
    justifyContent: 'center',
    marginBottom: 14,
  },
  sidebarNewChatText: {
    color: palette.textOnAccent,
    fontSize: 14,
    fontWeight: '600',
  },
  sidebarProjectBlock: {
    marginBottom: 12,
    gap: 6,
  },
  sidebarProjectLabel: {
    color: palette.textSecondary,
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  sidebarSearchBox: {
    height: 36,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    marginBottom: 14,
  },
  sidebarSearchInput: {
    flex: 1,
    minWidth: 0,
    color: palette.text,
    fontSize: 14,
    lineHeight: 20,
    paddingVertical: 0,
    outlineStyle: 'none' as never,
  },
  sidebarSearchClear: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sidebarSection: {
    flex: 1,
  },
  sidebarSectionTitle: {
    color: palette.textSecondary,
    fontSize: 11,
    fontWeight: '600',
    marginBottom: 8,
    letterSpacing: 0.3,
  },
  sidebarConversationList: {
    flex: 1,
  },
  sidebarConversationListContent: {
    gap: 6,
    paddingBottom: 20,
  },
  sidebarConversationItem: {
    borderRadius: radii.md,
    paddingHorizontal: 8,
    paddingVertical: 8,
    gap: 6,
  },
  sidebarConversationItemActive: {
    backgroundColor: palette.surfaceAlt,
  },
  sidebarConversationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  sidebarConversationContent: {
    flex: 1,
    minWidth: 0,
    gap: 4,
    paddingVertical: 2,
  },
  sidebarConversationTitleRow: {
    minHeight: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  sidebarConversationTitle: {
    flex: 1,
    minWidth: 0,
    color: palette.text,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '600',
  },
  sidebarConversationTitleActive: {
    color: palette.accentText,
  },
  sidebarConversationMetaRow: {
    minHeight: 22,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  sidebarConversationMeta: {
    flex: 1,
    minWidth: 0,
    color: palette.textSecondary,
    fontSize: 12,
    lineHeight: 16,
  },
  sidebarConversationMore: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surface,
  },
  sidebarConversationMoreActive: {
    backgroundColor: palette.surfaceAlt,
    borderWidth: 1,
    borderColor: palette.accentBorder,
  },
  sidebarConversationActionMenu: {
    position: 'absolute',
    right: 20,
    zIndex: 31,
    elevation: 31,
    width: 184,
    borderRadius: radii.md,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 22,
  },
  sidebarConversationFrost: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 30,
    elevation: 30,
    backgroundColor: palette.frostedSurface,
    ...(Platform.OS === 'web'
      ? ({
          backdropFilter: 'blur(14px)',
          WebkitBackdropFilter: 'blur(14px)',
        } as any)
      : {}),
  },
  sidebarConversationFrostTapTarget: {
    flex: 1,
  },
  sidebarConversationActionRow: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
  },
  sidebarConversationActionDangerRow: {
    borderBottomWidth: 0,
  },
  sidebarConversationActionText: {
    flex: 1,
    minWidth: 0,
    color: palette.text,
    fontSize: 13,
    fontWeight: '700',
  },
  sidebarConversationActionDangerText: {
    color: palette.danger,
  },
  sidebarEmpty: {
    color: palette.placeholder,
    fontSize: 14,
  },
  modalKeyboard: {
    flex: 1,
  },
  renameDialogScrim: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.scrim,
    paddingHorizontal: 28,
    zIndex: 1000,
    elevation: 1000,
    ...(Platform.OS === 'web'
      ? ({
          position: 'fixed',
          inset: 0,
        } as any)
      : {}),
  },
  renameDialog: {
    width: '100%',
    maxWidth: 380,
    minWidth: 0,
    borderRadius: radii.lg,
    backgroundColor: palette.bg,
    padding: 18,
    gap: 14,
    zIndex: 1001,
    elevation: 1001,
  },
  renameDialogTitle: {
    color: palette.text,
    fontSize: 18,
    fontWeight: '800',
  },
  renameDialogInput: {
    minHeight: 44,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    color: palette.text,
    fontSize: 15,
    paddingHorizontal: 12,
    paddingVertical: 8,
    ...(Platform.OS === 'web' ? { outlineStyle: 'none' } as any : {}),
  },
  renameDialogActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
  },
  renameDialogSecondaryButton: {
    minWidth: 72,
    height: 38,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  renameDialogSecondaryText: {
    color: palette.textSecondary,
    fontSize: 14,
    fontWeight: '700',
  },
  renameDialogPrimaryButton: {
    minWidth: 72,
    height: 38,
    borderRadius: radii.sm,
    backgroundColor: palette.accent,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  renameDialogPrimaryText: {
    color: palette.textOnAccent,
    fontSize: 14,
    fontWeight: '800',
  },
  deleteConfirmScrim: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.scrim,
    paddingHorizontal: 30,
    zIndex: 1000,
    elevation: 1000,
    ...(Platform.OS === 'web'
      ? ({
          position: 'fixed',
          inset: 0,
        } as any)
      : {}),
  },
  deleteConfirmDialog: {
    width: '100%',
    maxWidth: 340,
    minWidth: 0,
    borderRadius: radii.lg,
    backgroundColor: palette.bg,
    padding: 18,
    gap: 12,
    zIndex: 1001,
    elevation: 1001,
  },
  deleteConfirmIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: palette.dangerBg,
    borderWidth: 1,
    borderColor: palette.dangerBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteConfirmTitle: {
    color: palette.text,
    fontSize: 18,
    fontWeight: '800',
  },
  deleteConfirmText: {
    color: palette.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  deleteConfirmButton: {
    minWidth: 72,
    height: 38,
    borderRadius: radii.sm,
    backgroundColor: palette.danger,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  deleteConfirmButtonText: {
    color: palette.textOnDanger,
    fontSize: 14,
    fontWeight: '800',
  },
  deleteConfirmDescription: {
    color: palette.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  providerWizardError: {
    color: palette.danger,
    fontSize: 12,
    lineHeight: 18,
  },
  providerWizardWarning: {
    color: palette.warning,
    fontSize: 12,
    lineHeight: 18,
  },
  capabilityMatrixTable: {
    paddingTop: 8,
    paddingBottom: 4,
  },
  capabilityMatrixHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: palette.borderStrong,
    backgroundColor: palette.surface,
  },
  capabilityMatrixRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 38,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: palette.border,
  },
  capabilityMatrixModelCell: {
    width: 160,
    paddingHorizontal: 10,
    paddingVertical: 8,
    color: palette.text,
    fontSize: 12,
    fontWeight: '600',
  },
  capabilityMatrixCell: {
    width: 54,
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
    color: palette.textSecondary,
    fontSize: 11,
  },
  capabilityMatrixHeaderText: {
    color: palette.textSecondary,
    fontSize: 11,
    fontWeight: '800',
  },
  capabilityMatrixProviderOnly: {
    color: palette.warning,
    fontSize: 11,
    fontWeight: '800',
  },
  capabilityMatrixUnavailable: {
    color: palette.textMutedSolid,
    fontSize: 14,
  },
  sidebarProjectRow: {
    gap: 6,
    paddingVertical: 0,
    paddingRight: 4,
  },
  sidebarProjectChip: {
    maxWidth: 140,
    minHeight: 26,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 9,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: 'transparent',
  },
  sidebarProjectChipActive: {
    backgroundColor: palette.accentSoft,
    borderColor: palette.accentBorder,
  },
  sidebarProjectChipText: {
    flexShrink: 1,
    color: palette.textSecondary,
    fontSize: 11,
    fontWeight: '600',
  },
  sidebarProjectChipTextActive: {
    color: palette.accentText,
  },
  globalSearchResultRow: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    paddingHorizontal: 11,
    paddingVertical: 10,
    gap: 5,
  },
  globalSearchResultHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  globalSearchResultTitle: {
    flex: 1,
    color: palette.text,
    fontSize: 13,
    fontWeight: '700',
  },
  globalSearchResultKind: {
    color: palette.textSecondary,
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  globalSearchResultSnippet: {
    color: palette.textSecondary,
    fontSize: 11,
    lineHeight: 17,
  },
  projectMoveList: {
    maxHeight: 280,
  },
  projectMoveRow: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: palette.border,
  },
  projectMoveRowText: {
    flex: 1,
    color: palette.text,
    fontSize: 14,
    fontWeight: '700',
  },
  costGuardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  costGuardTodayRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    borderRadius: radii.md,
    backgroundColor: palette.surface,
    padding: 10,
  },
  usagePricingGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  usagePricingField: {
    flexGrow: 1,
    flexBasis: 150,
    minWidth: 0,
  },
  deleteConfirmActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
  },
  deleteConfirmCancelButton: {
    minWidth: 100,
    height: 38,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  deleteConfirmCancelText: {
    color: palette.textSecondary,
    fontSize: 13,
    fontWeight: '700',
  },
  deleteConfirmDeleteButton: {
    minWidth: 100,
    height: 38,
    borderRadius: radii.sm,
    backgroundColor: palette.accent,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  });
}

const appStylesByMode = {
  light: createChatPaneStyles(lightPalette),
  dark: createChatPaneStyles(darkPalette),
} as const;
