import { Platform, StyleSheet } from 'react-native';

import type { KelivoTheme } from '../../../ui/theme';

export function createSettingsToolsStyles(theme: KelivoTheme) {
  const { colors, radius } = theme;
  return StyleSheet.create({
    settingsCard: {
      backgroundColor: colors.surfaceAlt,
      borderRadius: radius.lg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.outline,
      padding: 16,
      gap: 14,
      marginHorizontal: 12,
    },
    settingsCardTitle: { color: colors.text, fontSize: 15, fontWeight: '600', marginBottom: 2 },
    settingsCardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    fieldGroup: { gap: 8 },
    fieldLabel: { color: colors.textSecondary, fontSize: 13, fontWeight: '600' },
    input: {
      minHeight: 44,
      borderRadius: radius.sm,
      borderWidth: 1,
      borderColor: colors.outline,
      backgroundColor: colors.background,
      paddingHorizontal: 14,
      color: colors.text,
      fontSize: 15,
      ...(Platform.OS === 'web' ? ({ outlineStyle: 'none' } as object) : {}),
    },
    multilineInput: { minHeight: 84, paddingTop: 12, paddingBottom: 12, textAlignVertical: 'top' },
    primaryButton: {
      height: 48,
      paddingHorizontal: 20,
      borderRadius: radius.pill,
      backgroundColor: colors.accent,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    primaryButtonText: { color: colors.textOnAccent, fontWeight: '600', fontSize: 15 },
    secondaryButton: {
      height: 40,
      minWidth: 60,
      paddingHorizontal: 16,
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: colors.borderStrong,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
      backgroundColor: colors.surface,
    },
    secondaryButtonText: { color: colors.text, fontWeight: '600', fontSize: 14 },
    iconButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.borderStrong,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surface,
    },
    buttonDisabled: { opacity: 0.5 },
    settingsNotice: { color: colors.warning, fontSize: 12, lineHeight: 18 },
    settingsEmptyState: {
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: colors.outline,
      backgroundColor: colors.background,
      paddingHorizontal: 12,
      paddingVertical: 11,
    },
    modelOverrideHint: { color: colors.textSecondary, fontSize: 12, lineHeight: 18 },
    providerChip: {
      height: 36,
      paddingHorizontal: 14,
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: colors.outline,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.background,
    },
    providerChipActive: { backgroundColor: colors.accent, borderColor: colors.accent },
    providerChipText: { color: colors.text, fontWeight: '500', fontSize: 14 },
    providerChipTextActive: { color: colors.textOnAccent },
    providerDeleteButton: {
      minHeight: 40,
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: colors.error,
      backgroundColor: colors.errorContainer,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
      paddingHorizontal: 14,
    },
    providerDeleteButtonText: { color: colors.error, fontSize: 13, fontWeight: '600' },
    providerRow: { gap: 10, paddingRight: 18, paddingVertical: 2 },
    projectPresetGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    projectPresetCard: {
      width: '48%',
      minHeight: 92,
      flexGrow: 1,
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: colors.outline,
      backgroundColor: colors.background,
      paddingHorizontal: 12,
      paddingVertical: 11,
      gap: 5,
    },
    projectPresetTitle: { color: colors.text, fontSize: 14, lineHeight: 19, fontWeight: '700' },
    projectPresetDescription: { color: colors.textSecondary, fontSize: 12, lineHeight: 17 },
    promptTemplateContentInput: { minHeight: 112, textAlignVertical: 'top', paddingTop: 12 },
    promptTemplateRow: {
      minHeight: 56,
      borderWidth: 1,
      borderColor: colors.outline,
      borderRadius: radius.md,
      backgroundColor: colors.background,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingLeft: 12,
      paddingRight: 4,
    },
    promptTemplateMain: { flex: 1, minWidth: 0, minHeight: 54, flexDirection: 'row', alignItems: 'center', gap: 9 },
    promptTemplateTextBlock: { flex: 1, minWidth: 0, gap: 2 },
    promptTemplateName: { color: colors.text, fontSize: 13, lineHeight: 18, fontWeight: '700' },
    pricingInputRow: { flexDirection: 'row', gap: 8 },
    pricingInputGroup: { flex: 1, minWidth: 0, gap: 5 },
    usageSummaryGrid: { flexDirection: 'row', gap: 8 },
    usageSummaryItem: { flex: 1, minWidth: 0, borderRadius: radius.md, backgroundColor: colors.background, paddingHorizontal: 10, paddingVertical: 12, gap: 3 },
    usageSummaryValue: { color: colors.text, fontSize: 18, lineHeight: 23, fontWeight: '800' },
    usageSummaryLabel: { color: colors.textSecondary, fontSize: 11, lineHeight: 16, fontWeight: '600' },
    usageCostRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 8 },
    usagePricingGrid: { gap: 10 },
    usagePricingField: { gap: 5 },
    mediaTaskRow: {
      minHeight: 58,
      borderWidth: 1,
      borderColor: colors.outline,
      borderRadius: radius.md,
      backgroundColor: colors.background,
      paddingLeft: 12,
      paddingRight: 4,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    mediaTaskInfo: { flex: 1, minWidth: 0, gap: 2 },
    mediaTaskState: { color: colors.textSecondary, fontSize: 11, lineHeight: 16, fontWeight: '700' },
    voiceTargetRow: {
      minHeight: 54,
      borderWidth: 1,
      borderColor: colors.outline,
      borderRadius: radius.md,
      backgroundColor: colors.background,
      paddingLeft: 12,
      paddingRight: 6,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    toolSegmentRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    toolSegment: { minHeight: 36, borderRadius: radius.pill, borderWidth: 1, borderColor: colors.outline, backgroundColor: colors.background, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 13 },
    toolSegmentActive: { borderColor: colors.accent, backgroundColor: colors.accentSoft },
    toolSegmentText: { color: colors.textSecondary, fontSize: 12, fontWeight: '700' },
    toolSegmentTextActive: { color: colors.accentText },
    messageErrorText: { color: colors.error, fontSize: 12, lineHeight: 18 },
    updateActionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
    updateActionButton: { flexGrow: 1, minWidth: 132, minHeight: 44 },
    costGuardTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    costGuardTodayRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  });
}
